name: Cowsay workflow using bash script

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout action
          uses: actions/checkout@v4 

        - name: List files in directory
          run: ls -al
        
        - name: Execute cowsay bash script
          run: |
            chmod +x .github/workflows/cowsay-install.sh
            ./.github/workflows/cowsay-install.sh           