name: My First Github actions Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu:latest
        steps:
        - name: Checkout action
          uses: actions/checkout@v4 
             
        - name: Echo hello world
          run: echo "Hello World"
          
        - name: List Files
          run: ls
          
        - name: Show README
          run: cat README.md  


