name: Matrix Configuration

on: 
    push:
    workflow_dispatch: 
        
jobs:
    Deploy:
        strategy:                   ## Set startegy as matrix and inside it mentioned the variables in key-walue format.
          matrix:
            os: ['ubuntu-latest', 'ubuntu-20.0.4', 'windows-latest']        ## here we used key and array of strings format
            images: ['hello-world', 'alpine']
        runs-on: ${{ matrix.os }}
        steps:
        - name: Echo docker details
          run: docker info
          
        - name: Run Images on ${{ matrix.os }}
          run: docker run ${{ matrix.images }}
                          