name: Multi-Job Cowsay workflow 

on: 
    workflow_dispatch: 
    # schedule:
    #   - cron: "*/1 * * * *"

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout action
          uses: actions/checkout@v4 

        - name: Install Cowsay lib 
          run: sudo apt-get install -y cowsay
            
        - name: execute cowsay
          run: cowsay -f dragon "Hi i am a dragon" >> dragon.txt

        - name: Upload dragon file to next build
          uses: actions/upload-artifact@v4
          with:
            name: dragon-text-file
            path: dragon.txt  
    test_job_2:
        needs: [build_job_1]
        runs-on: ubuntu-latest
        steps:
        - name: Download dragon-text-file 
          uses: actions/download-artifact@v4
          with:
              name: dragon-text-file
              path: ./   
    
        - name: Show file contents
          run: ls -lrth     
        
        - name: check file created or not
          run: grep -i "dragon" dragon.txt

    run_job_3:
        needs: [test_job_2]
        concurrency: 
            group: prod-deployment
            cancel-in-progress: false    
        runs-on: ubuntu-latest
        steps:
        - name: Sleep for 10min
          timeout-minutes: 1
          run: sleep 6000s

        - name: Show file contents
          run: ls -lrth     
        
        - name: Download dragon-text-file 
          uses: actions/download-artifact@v4
          with:
              name: dragon-text-file
              path: ./   
          
        - name: Check the file content
          run: cat dragon.txt        